### ISSUE TITLE
Consider updating to Manifest v3

### ISSUE THREAD

**Issue by bartaz** [canonical/ubuntu-copy-docs#15]
New version of extension Manifest is available, extensions based on Manifest v2 may become deprecated and eventually unpublished at some point in the future.

As we are not using any specific extension APIs this should hopefully be straightforward (possibly just a version number change).

https://developer.chrome.com/docs/extensions/mv3/intro/

https://extensionworkshop.com/documentation/develop/manifest-v3-migration-guide/

**Comment by juanruitina** [comment]
Chrome is already flagging it up 🫠

![Screenshot 2024-10-17 at 13 47 28](https://github.com/user-attachments/assets/55567e32-bfbc-4726-8954-eb6063acc262)
![Screenshot 2024-10-17 at 13 48 25](https://github.com/user-attachments/assets/e3f821ce-cffa-4942-bf84-613e576f4335)

**Comment by bartaz** [comment]
Fixed by #19 (released as 1.3.0)
